version: "3"
services:
  soapdemo-postgres:
    image: postgres:latest
    container_name: soapdemo-postgres
    restart: always
    environment:
      POSTGRES_DB: 'soapdemo'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - soapdemo-postgre:/var/lib/postgresql/data
    ports:
      - 5410:5432
volumes:
  soapdemo-postgre: